CC:=clang
FLAGS:=-Wall -Wextra -pedantic -std=c99 -Wvla -Wfloat-equal -Werror

anagrams: anagrams.c
	$(CC) anagrams.c -o anagrams $(FLAGS)

a2: anagrams_2.c
	$(CC) anagrams_2.c -o a2 $(FLAGS)

ll: ll.c
	$(CC) ll.c -o ll